version: '3'

services:
  app:
    build: .
    container_name: codeflix
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

